CoinListingApp/Models/Listing.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinListingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Listing()
        {
            this.ListingViews = new HashSet<ListingView>();
            this.Offers = new HashSet<Offer>();
            this.PostageListings = new HashSet<PostageListing>();
            this.Watchings = new HashSet<Watching>();
            this.OrderListings = new HashSet<OrderListing>();
        }
    
        public int ListingID { get; set; }
        public int SellerD { get; set; }
        public int CategoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double QTY { get; set; }
        public byte AllowOffers { get; set; }
        public byte isHighlight { get; set; }
        public byte isBump { get; set; }
        public byte isActive { get; set; }
        public double Price { get; set; }
        public System.DateTime Expires { get; set; }
        public Nullable<System.DateTime> DeactivatedDate { get; set; }
        public string Photos { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> BumpExpires { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public int ActiveDays { get; set; }
        public Nullable<byte> PaymentType { get; set; }
        public string CoverImage { get; set; }
        public byte isArchived { get; set; }
        public Nullable<System.DateTime> SortDate { get; set; }
        public bool shipInTwotoFourWeek { get; set; }
        public bool shipInFourtoEightWeek { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListingView> ListingViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Offer> Offers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostageListing> PostageListings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Watching> Watchings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderListing> OrderListings { get; set; }
    }
}

CoinListingApp/Models/ListingView.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinListingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListingView
    {
        public int ID { get; set; }
        public System.DateTime DateViewed { get; set; }
        public int ListingID { get; set; }
    
        public virtual Listing Listing { get; set; }
    }
}

CoinListingApp/Controllers/ListingsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Text;
using System.Web;
using System.Web.Mvc;
using CoinListingApp.Models;
using CoinListingApp.Resources;
using CoinListingApp.Services;
using CoinListingApp.Services.Validation;
using CoinListingApp.Utils;
using PagedList;

//using CoinListingApp.Resources;
using PayPal;
using PayPal.Api;

namespace CoinListingApp.Controllers
{
    public class ListingsController : Controller
    {
        private const int MaxPhotosAllowed = 5;
        private static Random random = new Random();
        private readonly CreditService creditService = new CreditService();
        private readonly Entities db = new Entities();
        private readonly FavouriteService favouriteService = new FavouriteService();
        private readonly ListingService listingService = new ListingService();
        private readonly NotificationService notificationService = new NotificationService();
        private readonly OfferService offerService = new OfferService();
        private readonly OrderService orderService = new OrderService();
        private readonly PaymentService paymentService = new PaymentService();
        private readonly UserService userService = new UserService();
        private readonly WatchingService watchingService = new WatchingService();
        private PayPal.Api.Payment payment;

        //THIS METHOD IS NOT USED!
        public ActionResult AddListingAndGoToCheckoutV2(int id, int amount)
        {
            if (!userService.IsSignedUp())
            {
                TempData["StatusCode"] = (int)HttpStatusCode.Forbidden;
                TempData["StatusDescription"] = "You need to be signed in to checkout";

                return RedirectToAction("Login", "Account", new { returnUrl = "/listings/checkoutv2/" + id + "?amount=" + amount });
            }

            Models.Address address = userService.GetBusinessAddress();

            CheckoutPageV2 cp = new CheckoutPageV2
            {
                CheckoutListings = new List<CheckoutListing>(),
                //Listing = listing,
                //Amount = amount,
                Address = address,
                //PaymentMethod = listingService.GetListingPaymentMethod_(Listing.ListingID)
            };

            var cart = Session["Cart"] as List<ItemCartViewModel>;

            if (cart != null)
            {
                foreach (var item in cart)
                {
                    Listing listingDb = db.Listings.Find(item.IdListing);

                    cp.CheckoutListings.Add(new CheckoutListing() { Listing = listingDb, Quantity = item.Qty });
                }
            }

            Listing listing = db.Listings.Find(id);
            cp.CheckoutListings.Add(new CheckoutListing() { Listing = listing, Quantity = amount });
            cp.SelectedPostageListing = cp.CheckoutListings.SelectMany(o => o.Listing.PostageListings).OrderByDescending(pl => pl.Price).FirstOrDefault();
            cp.PostageListings = cp.CheckoutListings.SelectMany(o => o.Listing.PostageListings).GroupBy(g => g.PostageID).Select(s => s.First()).ToList();
            cp.PaymentMethod = listingService.GetListingPaymentMethod_(id);

            return View("CheckoutV2", cp);
        }

        // ===== PAYPAL ONLY =====
        public ActionResult BuyNow(int id, string Cancel = null)
        {
            //Find all the necessary information
            Models.Order order = db.Orders.Find(id);

            if (order == null)
            {
                return View("Details", id);
            }

            //getting the apiContext
            APIContext apiContext = PaypalConfiguration.GetAPIContext();
            try
            {
                string payerId = Request.Params["PayerID"];

                var guid = Request.Params["guid"];
                var paymentId = Request.Params["paymentId"];
                var executedPayment = ExecutePayment(apiContext, payerId, paymentId);
                if (executedPayment.state.ToLower() != "approved")
                {
                    TempData["StatusCode"] = (int)HttpStatusCode.BadRequest;
                    TempData["StatusDescription"] = "Purchase for this listing failed. Please try again.";

                    System.Diagnostics.Debug.WriteLine("Failed");

                    return View("Details", new { id });
                }
            }
            catch (PaymentsException ex)
            {
                System.Diagnostics.Debug.WriteLine(ex.Data);
                System.Diagnostics.Debug.WriteLine(ex.Details);
                System.Diagnostics.Debug.WriteLine(ex.Message);
                System.Diagnostics.Debug.WriteLine(ex.Request);
                System.Diagnostics.Debug.WriteLine(ex.Response);
                System.Diagnostics.Debug.WriteLine(ex.StatusCode);
                System.Diagnostics.Debug.WriteLine(ex.WebExceptionStatus);
                System.Diagnostics.Debug.WriteLine(ex.StackTrace);

                TempData["StatusCode"] = (int)HttpStatusCode.BadRequest;
                TempData["StatusDescription"] = "Purchase for this listing failed. Please try again.";

                System.Diagnostics.Debug.WriteLine("Failed");

                return View("Details", new { id });
            }
            catch (Exception ex)
            {
                TempData["StatusCode"] = (int)HttpStatusCode.BadRequest;
                TempData["StatusDescription"] = "Purchase for this listing failed. Please try again.";

                System.Diagnostics.Debug.WriteLine("Failed");

                return View("Details", new { id });
            }

            //The purchase was successful -> update order state

            var updateStatus = orderService.OrderPaypalPayment(order);

            if (updateStatus == false)
            {
                TempData["StatusCode"] = (int)HttpStatusCode.BadRequest;
                TempData["StatusDescription"] = "The purchase of the listing was unsuccessful. Please try again";

                return RedirectToAction("Details", new { id });
            }

            Session["Cart"] = null;

            TempData["StatusCode"] = (int)HttpStatusCode.OK;
            TempData["StatusDescription"] = "The purchase of the listing was successful";

            return RedirectToAction("Index", "Orders");
        }

        // Checkout
        [HttpPost]
        public ActionResult CheckoutV2(CheckoutPageV2 checkoutPageV2)
        {
            //Check if user same as seller
            var currentUserId = this.userService.GetCurrentID();
            if (checkoutPageV2.CheckoutListings.Any(cl => cl.Listing.SellerD == currentUserId))
            {
                TempData["StatusCode"] = (int)HttpStatusCode.BadRequest;
                TempData["StatusDescription"] = "You are the seller of these listings.";

                return RedirectToAction("Index", "Home");
            }

            //TODO: PUT the properties of checkoutPageV2 in the view page so they don't come null ffs
            foreach (var checkoutListing in checkoutPageV2.CheckoutListings)
            {
                //Check if listing expired
                if (listingService.HasListingExpired(checkoutListing.Listing.ListingID))
                {
                    TempData["StatusCode"] = (int)HttpStatusCode.BadRequest;
                    TempData["StatusDescription"] = "The listing has expired. You will not be able to purchase this listing";

                    return RedirectToAction("Details", new { id = checkoutListing.Listing.ListingID });
                }

                //Check if order exists first if
                if (orderService.OpenOrderExists(checkoutListing.Listing.ListingID))
                {
                    TempData["StatusCode"] = (int)HttpStatusCode.BadRequest; TempData["StatusDescription"] = "An order for this listing exists. Please complete it before creating another one";

                    return RedirectToAction("Details", new { id = checkoutListing.Listing.ListingID });
                }
            }

            checkoutPageV2.SelectedPostageListing = checkoutPageV2.PostageListings.FirstOrDefault(p => p.Selected) ?? checkoutPageV2.PostageListings.FirstOrDefault();

            ListingBuyNowV2 listingBuyNowV2 = orderService.Convert(checkoutPageV2);
            //create order with CREATED status
            Models.Order order = orderService.BuyNowV2(listingBuyNowV2);

            if (listingBuyNowV2.PaymentMethod.ToLower().Contains("paypal"))
            {
                return this.HandlePaypalPayment(listingBuyNowV2, order);
            }
            else // EFT
            {
                //The purchase was successful -> continue
                //Update ORder status to PAYMENT PENDING

                bool resultConfirm = orderService.OrderNotPaypalPayment(order, listingBuyNowV2.SellerID);

                if (order == null)
                {
                    TempData["StatusCode"] = (int)HttpStatusCode.BadRequest;
                    TempData["StatusDescription"] = "The purchase of the listing was unsuccessful. Please try again";

                    return RedirectToAction("CheckoutV2", new { });
                }

                TempData["StatusCode"] = (int)HttpStatusCode.OK;
                TempData["StatusDescription"] = "Please send the payment to complete your order.";

                Session["Cart"] = null;

                return RedirectToAction("Payment", "Orders", new { id = order.OrderID });
            }
        }

        public ActionResult CheckoutV2()
        {
            if (!userService.IsSignedUp())
            {
                TempData["StatusCode"] = (int)HttpStatusCode.Forbidden;
                TempData["StatusDescription"] = "You need to be signed in to checkout";

CoinListingApp/Views/Listings/Checkout.cshtml
@model CoinListingApp.Models.CheckoutPage
@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Shared/_LayoutFront.cshtml";
}

<div id="main_wrapper">
    <div class="clearfix"></div>
    @*<div id="titlebar" class="gradient">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <h2>Choose Payment Option</h2>
                        <nav id="breadcrumbs">
                            <ul>
                                <li><a href="index_1.html">Home</a></li>
                                <li>Choose Payment Option</li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>*@
    <div class="container margin-bottom-75">
        <div class="row">
            <div class="col-lg-8 col-md-8 utf_listing_payment_section">
                @if (Model.PaymentMethod.Contains("EFT"))
                {
                    @*<label>WHAT DO WE NEED TO SHOW HERE??</label>*@
                    <div class="utf_booking_listing_section_form margin-bottom-40">
                        @*<h3><i class="sl sl-icon-paper-plane"></i> Billing Information</h3>
                            <div class="row">
                                <div class="col-md-6">
                                    <label>First Name</label>
                                    <input type="text" value="" placeholder="First Name">
                                </div>
                                <div class="col-md-6">
                                    <label>Last Name</label>
                                    <input type="text" value="" placeholder="Last Name">
                                </div>
                                <div class="col-md-6">
                                    <div class="medium-icons">
                                        <label>E-Mail</label>
                                        <input type="text" value="" placeholder="Email">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="medium-icons">
                                        <label>Phone</label>
                                        <input type="text" value="" placeholder="Phone">
                                    </div>
                                </div>
                            </div>
                            <input type="button"  />*@
                        <a onclick="Buy();" class="button utf_booking_confirmation_button margin-top-20 margin-bottom-10">Confirm Now</a>
                    </div>
                }

                @if (Model.PaymentMethod.Contains("Paypal"))
                {
                    <div class="utf_booking_payment_option_form">
                        <h3><i class="sl sl-icon-credit-card "></i> Payment Method</h3>
                        <div class="payment">
                            <div class="utf_payment_tab_block">
                                <div class="utf_payment_trigger_tab">
                                    @*<input checked="" id="paypal" name="cardType" type="radio" value="paypal">*@
                                    <label for="paypal">PayPal Goods & Services</label>
                                    <img class="utf_payment_logo paypal" src="images/paypal_pay.png" alt="">
                                </div>
                            </div>

                            @*<div class="row">
                                    <div class="col-md-6">
                                        <div class="card-label">
                                            <label for="email">Email</label>
                                            <input id="email" name="email" required="" type="text">
                                        </div>
                                    </div>
                                </div>*@
                        </div>
                        <a onclick="Buy();" class="button utf_booking_confirmation_button margin-top-20 margin-bottom-10">Confirm Now</a>
                    </div>
                }
            </div>
            <div class="col-lg-4 col-md-4 margin-top-0 utf_listing_payment_section">
                <div class="utf_booking_listing_item_container compact utf_order_summary_widget_section">
                    <div class="listing-item">
                        <img src="~/Styles/UDUI/images/listing-item-04.jpg" alt="">
                        <div class="utf_listing_item_content">
                            <h3>Vintage Italian Beer Bar & Restaurant</h3>
                            <span><i class="sl sl-icon-location"></i> The Ritz-Carlton, Hong Kong</span>
                            <span><i class="sl sl-icon-phone"></i> (415) 796-3633</span>
                            <div class="utf_star_rating_section" data-rating="4.5">
                                <div class="utf_counter_star_rating">(18) Reviews</div>
                            </div>
                        </div>
                    </div>
                </div>
                @{
                    var price = @Model.Amount * @Model.Listing.Price;
                }
                <div class="boxed-widget opening-hours summary margin-top-0">
                    <h3><i class="fa fa-calendar-check-o"></i> Purchase Summary</h3>
                    <ul>
                        <li>Amount <span>@Model.Amount</span></li>
                        <li class="total-costs">Total Cost <span>@Math.Round(price, 2).ToString("N2")</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <script>

        function Buy() {

           // window.location.href = "~/Listings/BuyNow/@(Model.Listing.ListingID)?amount="+@Request.QueryString["amount"];
            window.location.href='@Url.Action("BuyNow", "Listings", new { id = Model.Listing.ListingID, amount = Request.QueryString["amount"] })';

            return false;

            }
    </script>

    <!-- Scripts -->
    <script src="scripts/jquery-3.4.1.min.js"></script>
    <script src="scripts/chosen.min.js"></script>
    <script src="scripts/slick.min.js"></script>
    <script src="scripts/rangeslider.min.js"></script>
    <script src="scripts/magnific-popup.min.js"></script>
    <script src="scripts/jquery-ui.min.js"></script>
    <script src="scripts/mmenu.js"></script>
    <script src="scripts/tooltips.min.js"></script>
    <script src="scripts/color_switcher.js"></script>
    <script src="scripts/jquery_custom.js"></script>

    <!-- Style Switcher -->
    <div id="color_switcher_preview">
        <h2>Choose Your Color <a href="#"><i class="fa fa-gear fa-spin (alias)"></i></a></h2>
        <div>
            <ul class="colors" id="color1">
                <li><a href="#" class="stylesheet"></a></li>
                <li><a href="#" class="stylesheet_1"></a></li>
                <li><a href="#" class="stylesheet_2"></a></li>
                <li><a href="#" class="stylesheet_3"></a></li>
                <li><a href="#" class="stylesheet_4"></a></li>
                <li><a href="#" class="stylesheet_5"></a></li>
            </ul>
        </div>
    </div>
</div>

CoinListingApp/Views/Listings/Delete.cshtml
@model CoinListingApp.Models.Listing

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutFront.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Listing</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QTY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QTY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllowOffers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllowOffers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isHighlight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isHighlight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isBump)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isBump)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.isActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Expires)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Expires)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeactivatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeactivatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ActiveDays)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ActiveDays)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Listings", "Users")
        </div>
    }
</div>

CoinListingApp/Views/Listings/Edit.cshtml
@model CoinListingApp.Models.Listing

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutFront.cshtml";
}

@Html.Partial("_Notify")

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Listing</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ListingID)

        <div class="form-group">
            @Html.LabelFor(model => model.SellerD, "SellerD", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SellerD", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SellerD, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QTY, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QTY, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QTY, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AllowOffers, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AllowOffers, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AllowOffers, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isHighlight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.isHighlight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.isHighlight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isBump, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.isBump, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.isBump, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.isActive, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.isActive, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.isActive, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Expires, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Expires, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Expires, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeactivatedDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeactivatedDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeactivatedDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ActiveDays, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ActiveDays, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ActiveDays, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Photos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Photos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CoinListingApp/Views/Listings/Index.cshtml
@model PagedList.IPagedList<CoinListingApp.Models.FullListing>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutFront.cshtml";
}

@Html.Partial("_TitleSection", null, new ViewDataDictionary { { "PageTitle", "Listings" } })

@Html.Partial("_Listings", Model)