CoinListingApp/Models/CreditHistory.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinListingApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditHistory
    {
        public int ID { get; set; }
        public string TransactionDetail { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
        public double Amount { get; set; }
        public double Price { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}

CoinListingApp/Controllers/CreditHistoriesController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text;
using System.Web.Mvc;
using CoinListingApp.Models;

namespace CoinListingApp.Controllers
{
    public class CreditHistoriesController : Controller
    {
        private Entities db = new Entities();

        // GET: CreditHistories/Create
        public ActionResult Create()
        {
            ViewBag.UserID = new SelectList(db.Users, "UserID", "Name");
            return View();
        }

        // POST: CreditHistories/Create To protect from overposting attacks, enable the specific
        // properties you want to bind to, for more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,TransactionDetail,DateOfPurchase,Amount,Price,UserID")] CreditHistory creditHistory)
        {
            if (ModelState.IsValid)
            {
                db.CreditHistories.Add(creditHistory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserID = new SelectList(db.Users, "UserID", "Name", creditHistory.UserID);
            return View(creditHistory);
        }

        // GET: CreditHistories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreditHistory creditHistory = db.CreditHistories.Find(id);
            if (creditHistory == null)
            {
                return HttpNotFound();
            }
            return View(creditHistory);
        }

        // POST: CreditHistories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CreditHistory creditHistory = db.CreditHistories.Find(id);
            db.CreditHistories.Remove(creditHistory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: CreditHistories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreditHistory creditHistory = db.CreditHistories.Find(id);
            if (creditHistory == null)
            {
                return HttpNotFound();
            }
            return View(creditHistory);
        }

        // GET: CreditHistories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CreditHistory creditHistory = db.CreditHistories.Find(id);
            if (creditHistory == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserID = new SelectList(db.Users, "UserID", "Name", creditHistory.UserID);
            return View(creditHistory);
        }

        // POST: CreditHistories/Edit/5 To protect from overposting attacks, enable the specific
        // properties you want to bind to, for more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,TransactionDetail,DateOfPurchase,Amount,Price,UserID")] CreditHistory creditHistory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(creditHistory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserID = new SelectList(db.Users, "UserID", "Name", creditHistory.UserID);
            return View(creditHistory);
        }

        [HttpPost]
        public ActionResult Export(DateTime? dateFrom, DateTime? dateTo)
        {
            if (!dateFrom.HasValue || !dateTo.HasValue || dateFrom.Value > dateTo.Value)
            {
                TempData["StatusCode"] = (int)HttpStatusCode.BadRequest;
                TempData["StatusDescription"] = "Please provide a valid \"date from\" and \"date to\" values";

                return RedirectToAction("Index");
            }

            var creditHistories = db.CreditHistories.Include(c => c.User);

            var filteredCreditHistories = creditHistories.Where(ch => ch.DateOfPurchase >= dateFrom.Value && ch.DateOfPurchase <= dateTo.Value);

            return this.BuildCsv(filteredCreditHistories, dateFrom.Value, dateTo.Value);
        }

        // GET: CreditHistories
        public ActionResult Index()
        {
            if (TempData["StatusCode"] != null)
            {
                TempData["StatusCode"] = (int)TempData["StatusCode"];
                TempData["StatusDescription"] = (string)TempData["StatusDescription"];
            }

            var creditHistories = db.CreditHistories.Include(c => c.User);
            return View(creditHistories.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private FileResult BuildCsv(IQueryable<CreditHistory> creditHistories, DateTime dateFrom, DateTime dateTo)
        {
            StringBuilder sb = new StringBuilder();
            string headers = $"Date of purchase, Transaction Detail, Amount, Price, User\r\n";

            sb.Append(headers);

            foreach (var creditTransaction in creditHistories)
            {
                sb.Append(CreditTransactionToString(creditTransaction));

                //Append new line character.
                sb.Append("\r\n");
            }

            var dateIntervalStr = $"{dateFrom.ToString("yyyy-MM-dd")}_{dateTo.ToString("yyyy-MM-dd")}";
            return File(Encoding.UTF8.GetBytes(sb.ToString()), "text/csv", $"credit_transactions_history_{dateIntervalStr}.csv");
        }

        private string CreditTransactionToString(CreditHistory creditTransaction)
        {
            return creditTransaction.DateOfPurchase
              + "," + creditTransaction.TransactionDetail
              + "," + creditTransaction.Amount
              + "," + creditTransaction.Price
              + "," + creditTransaction.User.Name + " " + creditTransaction.User.Surname;
        }
    }
}

CoinListingApp/Views/CreditHistories/Create.cshtml
@model CoinListingApp.Models.CreditHistory

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreditHistory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TransactionDetail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransactionDetail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransactionDetail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfPurchase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfPurchase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfPurchase, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CoinListingApp/Views/CreditHistories/Delete.cshtml
@model CoinListingApp.Models.CreditHistory

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CreditHistory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TransactionDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransactionDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfPurchase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfPurchase)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

CoinListingApp/Views/CreditHistories/Details.cshtml
@model CoinListingApp.Models.CreditHistory

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Details</h2>

<div>
    <h4>CreditHistory</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TransactionDetail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransactionDetail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateOfPurchase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateOfPurchase)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

CoinListingApp/Views/CreditHistories/Edit.cshtml
@model CoinListingApp.Models.CreditHistory

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreditHistory</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.TransactionDetail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransactionDetail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TransactionDetail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfPurchase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DateOfPurchase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfPurchase, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CoinListingApp/Views/CreditHistories/Index.cshtml
@model IEnumerable<CoinListingApp.Models.CreditHistory>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@Html.Partial("_Notify")

<h2>Export Transaction History</h2>

@using (Html.BeginForm(Html.BeginForm("Export", "CreditHistories", FormMethod.Post)))
{
    <div class="row">
        <div class=" col-md-2">
            <h5>Date From:</h5>
            @Html.TextBox("dateFrom", ViewBag.DateFrom as string, new { @type = "Date" })
        </div>

        <div class="col-md-2">
            <h5>Date To:</h5>
            @Html.TextBox("dateTo", ViewBag.DateTo as string, new { @type = "Date" })
        </div>
        <div class="col-md-2">
            <br />
            <input class="btn btn-success" type="submit" value="Export to CSV" />
        </div>
    </div>
}

<hr />

<h2>Transaction History</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TransactionDetail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateOfPurchase)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionDetail)
            </td>
            <td>
                @item.DateOfPurchase.ToString("dd/MM/yyyy HH:mm")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.User.Name)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ID })
        </tr>
    }
</table>